gaapiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-boot-service-deployment
spec:
  replicas: 2 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: spring-mongodb-crud-application
    spec:
      containers:
        - name: spring-mongodb-crud-application
          image: gapaa/spring-mongodb-crud-application
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: mongo-service